# Generated by Django 3.1.7 on 2021-12-01 12:34

import chat.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/avatar/', location='D:\\Users\\elmarceloc\\Downloads\\django-master\\media/avatar/'), upload_to=chat.models.image_directory_path),
        ),
    ]
