# Generated by Django 3.1.7 on 2021-12-01 14:09

import chat.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20211201_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='chat.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/avatar/', location='D:\\Users\\elmarceloc\\Downloads\\django-master\\media/avatar/'), upload_to=chat.models.image_directory_path),
        ),
    ]
