# Generated by Django 3.1.7 on 2021-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211201_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default='', max_length=255),
        ),
    ]
