# Generated by Django 3.1.7 on 2021-12-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20211201_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
