# Generated by Django 3.1.7 on 2021-12-10 06:19

import chat.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20211203_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/chatroom/', location='D:\\Users\\elmarceloc\\Downloads\\Lobster-main\\media/chatroom/'), upload_to=chat.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/avatar/', location='D:\\Users\\elmarceloc\\Downloads\\Lobster-main\\media/avatar/'), upload_to=chat.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
