# Generated by Django 3.1.7 on 2021-12-10 07:38

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('chat', '0012_auto_20211210_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
