# Generated by Django 3.1.7 on 2021-12-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chatroomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chat.customuser'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatRoomUser',
        ),
    ]
