# Generated by Django 3.1.7 on 2021-12-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20211210_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discord',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
