# Generated by Django 3.1.7 on 2021-12-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20211210_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='status',
            new_name='room',
        ),
    ]
