# Generated by Django 3.1.7 on 2021-12-10 16:43

import chat.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20211210_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/chatroom/', location='C:\\Users\\sophi\\OneDrive\\Desktop\\Lobster\\media/chatroom/'), upload_to=chat.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/avatar/', location='C:\\Users\\sophi\\OneDrive\\Desktop\\Lobster\\media/avatar/'), upload_to=chat.models.image_directory_path),
        ),
    ]
