# Generated by Django 3.1.7 on 2024-11-07 17:49

import chat.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_auto_20211210_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/chatroom/', location='C:\\Users\\retam\\workspace\\UTFSM\\2021-2\\Lobster\\media/chatroom/'), upload_to=chat.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/avatar/', location='C:\\Users\\retam\\workspace\\UTFSM\\2021-2\\Lobster\\media/avatar/'), upload_to=chat.models.image_directory_path),
        ),
    ]
